name: CI Pipeline

on:
  push:
    branches: [ "main", "release" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Log in to Docker Hub
      run: echo ${{secrets.DOCKER_PASSWORD}} | docker login --username ${{secrets.DOCKER_USERNAME}} --password-stdin

    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: echo Teste1234 | docker login --username dash7 --password-stdin

    - name: Build the Docker image
      run: docker build -t dash7/codeflix .
    - name: Push to Dockerhub
      run: docker push dash7/codeflix:latest


