name: CI Pipeline

on:
  push:
    branches: [ "main", "release" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
    - name: Login Dockerhub
      run: echo ${{secrets.DOCKER_PASSWORD}} | docker login --username dash7 --password-stdin

    - name: Build the Docker image
      run: docker build --rm -t dash7/codeflix -f Codeflix.Catalog.Api/Dockerfile .
    - name: Push to Dockerhub
      run: docker push dash7/codeflix:latest


